// Generated by Wrangler by running `wrangler types`

interface Env {
	DB: D1Database;
	DB_PREVIEW: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	VAPID_EMAIL: string;
	VAPID_PUBLIC_KEY: string;
	VAPID_PRIVATE_KEY: string;
}
