// Generated by Wrangler by running `wrangler types`

interface Env {
	DB: D1Database;
	DB_PREVIEW: D1Database;
	ANALYTICS: AnalyticsEngineDataset;
	NOTIFICATION_QUEUE: Queue;
	VAPID_PRIVATE_KEY: string;
}
